### PR TITLE
Add archive relay docker image

### PR DESCRIPTION
**Pull request by MartinOndejka**
Replaces https://github.com/zeko-labs/zeko/blob/942d4306678fcd261ab5306bc0944b8424fcff57/src/app/zeko/sequencer/Dockerfile#L271

### CODE REVIEW

**Comment by L-as** [comment]
PR description please

**Comment by MartinOndejka** [comment]
> PR description please

I don't know what else should I write apart from maybe repeating the title.

**Comment by L-as** [comment]
What’s the reason for adding it? Why wasn’t it here before?

**Comment by MartinOndejka** [comment]
> What’s the reason for adding it? Why wasn’t it here before?

It wasn't built using nix, I've added it for the consistency.

**Pull request merged**
